### ISSUE TITLE
Bitgen on Ubuntu Linux

### ISSUE THREAD

**Issue by VlaDDD0S** [Anarbb/BitGen#18]
please tell me how to run bitgen on ubuntu?

**Comment by Fr1edly** [comment]
like any other system.
Open your terminal
pip install -r requirements.txt
python main.py

**Comment by Fr1edly** [comment]
> please tell me how to run bitgen on ubuntu?

like any other system.
Open your terminal
pip install -r requirements.txt
python main.py
