### ISSUE TITLE
BitGen doesn't save output file

### ISSUE THREAD

**Issue by Michal-Dudcenko** [Anarbb/BitGen#23]
BitGen doesn't save output file:

![image](https://user-images.githubusercontent.com/87039655/177040196-db8a66d7-1b78-49bd-a680-341168b56e4c.png)
![image](https://user-images.githubusercontent.com/87039655/177040199-1b9c071f-84b7-44bc-ae47-5c90d341e5d6.png)

This program was made by Anarb and it generates Bitcoin by searching multiple possible
wallet combinations until it's finds one with over 0 BTC and saves it into

a file called "wet.txt" in the results folder.
It's recommended to leave this running for a long time to get the best resaults, It's doesn't use up
that much resources so you can leave it in the background in the chance of you hitting a jackpot.
It's like mining but with less resources

Modyfied by:
@Anonymousl33t TikTok
@anonymousl337 Telegram

threads: 1500
save dry wallets: y

Address: 1Mu53TU3TC3bUjMYT5u11NnrUFuCCKbHZE | Balance: None | Mnemonic phrase: circle forum verb reject more fame clean learn evil push million release
Address: 1JWt97w3uDngVYR4cjSLLGfi4j93ez8MT9 | Balance: None | Mnemonic phrase: antenna frog flush warfare oxygen worth disorder race intact nest release sheriff
Address: 158y4x69HoEPmVxaJMQ5ErcCHTKtMzmqiC | Balance: None | Mnemonic phrase: hurdle seat thrive helmet vapor face congress quarter master can alien security
Address: 12PJP5VVZSTPY2ZPrJ6LNzsDRxaCT7ZEGN | Balance: None | Mnemonic phrase: shoot news adjust disagree reopen body found alcohol man hungry bread already
Address: 1M8XszrDVXFqxaPVMFhziNSE9qpRcydvCE | Balance: None | Mnemonic phrase: swing narrow machine slim scatter tenant wreck joke nurse sunny amazing leisure
Address: 15rVeKei88jyxT3xZkBv1386RA65cPd6hg | Balance: None | Mnemonic phrase: exist buddy obtain hedgehog diary noodle bar jewel absurd ridge stomach cancel
Address: 1A74Uc8nDfzBiaQFW6fBE8SphB2JW3jnGm | Balance: None | Mnemonic phrase: raccoon accuse runway hurt street crystal obey observe cram pluck soldier age
Address: 19nrUXtcijj35SgTWGvWnrWTrBrceQYaLG | Balance: None | Mnemonic phrase: trap ride symptom rifle approve usage fashion swap basket shell segment fatal
Address: 1Gdyf3jd6GppE5nSXs1fsFnkzY8j7x2wtU | Balance: None | Mnemonic phrase: atom rubber select basic woman tower trap warrior engage normal entry juice
Address: 1B64hdeVDkzkFAGDcbVjYaHhoUcuYLxYKL | Balance: None | Mnemonic phrase: tower candy fee bracket receive mask glue raven scheme jewel rifle elite
Address: 1Ks4dTkh1a6n3giuzvvMNYNzCnpU8K4SSJ | Balance: None | Mnemonic phrase: shine purity spare fence need quality avoid shift effort human artist art
Address: 144Lfe4DvnRy3t2G5C2DaAQzvyCRXYFVH5 | Balance: None | Mnemonic phrase: grass picture mixture rail day enhance switch extra wedding build circle fever
**_And other..._**

**Comment by Hail2Hydra** [comment]
> 

Dear @Anas i hope im not stepping out of bounds in replying .
But wanted to leaned a hand to simple issue .

You need to edit line #24 in main.py Script. here is simple example 

parser.add_argument(
    "-s",
    "--savedry",
    help="save empty wallets",
    action="store_true",
    default=False,

So just change     (default=False   TO     default=True

It will save empty to dry file 

you dont even need to this Part you can pretend that isnt not even there wont affect the function your trying to achieve 
( use parser.add_argument(
    "-s",
    "--savedry",)

**Comment by Hail2Hydra** [comment]
Ello my good sir @Michal-Dudcenko 

Dear @Anas i hope im not stepping out of bounds in replying .
But wanted to leaned a hand to simple issue .

You need to edit line #24 in main.py Script. here is simple example 

parser.add_argument(
    "-s",
    "--savedry",
    help="save empty wallets",
    action="store_true",
    default=False,


So just change     (default=False   TO     default=True

It will save empty to dry file 

you dont even need to this Part you can pretend that isnt not even there wont affect hte fucntion your trying to achive 
( use parser.add_argument(
    "-s",
    "--savedry",)

**Comment by Hail2Hydra** [comment]
You dont even have to use  parser.add_argument in your one liner to start the script . Change it from False to True  and than launch it  :)

**Comment by Hail2Hydra** [comment]
apologize now for Horrible grammar . hope im still being understood

**Comment by Anarbb** [comment]
it should be working now, just add the argument -s to save empty wallets (not recommended)
