### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by oleg80pop1** [Anarbb/BitGen#3]
Hello, I tried your new script, it works in the terminal. But when I ran the netstat program, I didn’t see any connection associated with the program.

**Comment by Anarbb** [comment]
Can you elaborate?

**Comment by oleg80pop1** [comment]
This program does not make inquiries about the availability of the balance of the wallet on the Internet. It just generates addresses and shows zero balance.

**Comment by Anarbb** [comment]
It rare for you to find a wallet that has a balance, and it does check against an API if you read the code you can see that.
