### ISSUE TITLE
Where is mnemonic phrase ?

### ISSUE THREAD

**Issue by ilyasky87** [Anarbb/BitGen#6]
Anarb hello bro! Tell me how to make the program output a mnemonic phrase and not a private key? you need just the phrase to restore... can you help me with this problem.Tell me plz => troy8781@gmail.com

**Comment by Anarbb** [comment]
I'll add an option to do that soon.

**Comment by KitTiMamyMav** [comment]
"Can you tell me how to make the program output a mnemonic phrase rather than a private key?" 

Have you already added this function or not yet?

**Comment by KitTiMamyMav** [comment]
> I'll add an option to do that soon.

Have you already added this function or not yet?

**Comment by Anarbb** [comment]
I am still working on it the library I'm using doesn't support them so might switch that out,
Currently Adding multiple coin support for the mean time

**Comment by KitTiMamyMav** [comment]
> Я все еще работаю над этим, библиотека, которую я использую, не поддерживает их, поэтому могу отключить это, в настоящее время добавляется поддержка нескольких монет в среднем

Is it possible to access a bitcoin wallet without a mnemonic phrase using a private key?
